//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPOINTMENT()
        {
            this.APPOINTMENT_ext = new HashSet<APPOINTMENT_ext>();
        }
    
        public long id { get; set; }
        public Nullable<long> rel_ref_APPOINTMENT_type_id { get; set; }
        public Nullable<long> rel_ref_APPOINTMENT_status_id { get; set; }
        public Nullable<long> rel_SOUL_id { get; set; }
        public Nullable<long> rel_ref_status_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<long> timezone { get; set; }
        public System.DateTime dt_create { get; set; }
        public Nullable<long> create_by__USER_id { get; set; }
        public Nullable<System.DateTime> dt_update { get; set; }
        public Nullable<long> update_by__USER_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOINTMENT_ext> APPOINTMENT_ext { get; set; }
        public virtual ref_APPOINTMENT_status ref_APPOINTMENT_status { get; set; }
        public virtual ref_APPOINTMENT_type ref_APPOINTMENT_type { get; set; }
    }
}
