//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INS_info_2
    {
        public long id { get; set; }
        public string benefit_level { get; set; }
        public Nullable<bool> DME_benefits { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<decimal> deductible { get; set; }
        public Nullable<decimal> deductible_met { get; set; }
        public Nullable<double> percent_coverage { get; set; }
        public Nullable<decimal> out_of_pocket { get; set; }
        public Nullable<bool> co_pay { get; set; }
        public Nullable<decimal> co_pay_amount { get; set; }
        public Nullable<bool> preauth_req { get; set; }
        public string preauth_contact { get; set; }
        public string payor_id { get; set; }
        public string preauth_info { get; set; }
    }
}
