//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_USER
    {
        public long id { get; set; }
        public Nullable<long> rel_USER_id { get; set; }
        public string action_note { get; set; }
        public Nullable<long> rel_ref_action_id { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string ip { get; set; }
        public string page { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
