//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_Q1
    {
        public long id { get; set; }
        public long acct_manager { get; set; }
        public long rel_ref_orprocstate_id { get; set; }
        public long count { get; set; }
        public string order_ids { get; set; }
        public System.DateTime date { get; set; }
    }
}
