//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_EXTERNAL
    {
        public long id { get; set; }
        public Nullable<long> rel_ref_external_type_id { get; set; }
        public string external_type { get; set; }
        public string data_out { get; set; }
        public string data_in { get; set; }
        public string meta { get; set; }
        public System.DateTime timestamp { get; set; }
        public Nullable<long> rel_SOUL_id { get; set; }
        public Nullable<long> executed_by { get; set; }
        public Nullable<long> rel_ORPROC_id { get; set; }
    }
}
