//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERPROC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERPROC()
        {
            this.ORDER_info_2 = new HashSet<ORDER_info_2>();
            this.ORDER_shipping = new HashSet<ORDER_shipping>();
            this.TAGs1 = new HashSet<TAG>();
        }
    
        public long id { get; set; }
        public long rel_TRANSACTION_id { get; set; }
        public long rel_ref_orproc_state_id { get; set; }
        public Nullable<long> taken_by { get; set; }
        public Nullable<System.DateTime> taken_on { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<long> last_update_by { get; set; }
        public long rel_ITEM_id { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string meta { get; set; }
        public Nullable<bool> stay_taken { get; set; }
        public Nullable<long> acct_managed_by { get; set; }
        public string tags { get; set; }
        public string tags_sys { get; set; }
    
        public virtual con_ORDERPROC_DOCTOR con_ORDERPROC_DOCTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_info_2> ORDER_info_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_shipping> ORDER_shipping { get; set; }
        public virtual ref_orproc_state ref_orproc_state { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG> TAGs1 { get; set; }
    }
}
