//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_shipping
    {
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public string trackng_number { get; set; }
        public Nullable<long> rel_ref_shipping_status_id { get; set; }
        public string notes { get; set; }
        public long rel_ORDERPROC_id { get; set; }
    
        public virtual ORDERPROC ORDERPROC { get; set; }
    }
}
