//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_zip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ref_zip()
        {
            this.DOCTORs = new HashSet<DOCTOR>();
            this.DOCTOR_NPI = new HashSet<DOCTOR_NPI>();
            this.hs_DOCTOR = new HashSet<hs_DOCTOR>();
            this.hs_DOCTOR1 = new HashSet<hs_DOCTOR>();
            this.hs_Hospital = new HashSet<hs_Hospital>();
            this.hs_ORGANIZATION = new HashSet<hs_ORGANIZATION>();
            this.SOULs = new HashSet<SOUL>();
        }
    
        public long id { get; set; }
        public string zip { get; set; }
        public string city_name { get; set; }
        public string city_state { get; set; }
        public string city_state_long { get; set; }
        public double city_lat { get; set; }
        public double city_lon { get; set; }
        public string city_county { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTOR> DOCTORs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTOR_NPI> DOCTOR_NPI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hs_DOCTOR> hs_DOCTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hs_DOCTOR> hs_DOCTOR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hs_Hospital> hs_Hospital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hs_ORGANIZATION> hs_ORGANIZATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOUL> SOULs { get; set; }
    }
}
