//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOUL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOUL()
        {
            this.con_SOUL_LIST = new HashSet<con_SOUL_LIST>();
            this.con_SOUL_ref_insurance = new HashSet<con_SOUL_ref_insurance>();
            this.SOUL_ext = new HashSet<SOUL_ext>();
            this.wellness_exam = new HashSet<wellness_exam>();
        }
    
        public long id { get; set; }
        public string name_first { get; set; }
        public string name_last { get; set; }
        public string phone { get; set; }
        public string addr_address1 { get; set; }
        public string addr_address2 { get; set; }
        public Nullable<long> addr_rel_ref_zip_id { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string salutation { get; set; }
        public Nullable<bool> is_prime { get; set; }
        public System.DateTime dt_create { get; set; }
        public Nullable<System.DateTime> dt_update { get; set; }
        public long create_by__USER_id { get; set; }
        public Nullable<long> update_by__USER_id { get; set; }
        public Nullable<long> taken_by__USER_id { get; set; }
        public Nullable<System.DateTime> dt_taken { get; set; }
        public long rel_ref_status_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<con_SOUL_LIST> con_SOUL_LIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<con_SOUL_ref_insurance> con_SOUL_ref_insurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOUL_ext> SOUL_ext { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wellness_exam> wellness_exam { get; set; }
        public virtual ref_zip ref_zip { get; set; }
    }
}
