//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSOUL
    {
        public long id { get; set; }
        public string name_first { get; set; }
        public string name_last { get; set; }
        public string phone_number { get; set; }
        public long rel_ADDRESS_id { get; set; }
        public string email { get; set; }
        public string meta { get; set; }
        public string OR_LIST_res_code { get; set; }
        public Nullable<System.DateTime> last_contact { get; set; }
        public Nullable<long> last_contact_by { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<long> last_update_by { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string alt_name { get; set; }
        public string alt_phone { get; set; }
        public string alt_relationship { get; set; }
    }
}
