
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api.Models
{

using System;
    using System.Collections.Generic;
    
public partial class con_USER_favorite_DOCTOR
{

    public int id { get; set; }

    public long rel_doctor_id { get; set; }

    public Nullable<bool> favor { get; set; }

    public System.DateTime dt_create { get; set; }

    public long create_by__USER_id { get; set; }

    public Nullable<System.DateTime> dt_update { get; set; }

    public Nullable<long> update_by__USER_id { get; set; }



    public virtual hs_DOCTOR hs_DOCTOR { get; set; }

}

}
