
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api.Models
{

using System;
    using System.Collections.Generic;
    
public partial class log_payment
{

    public long id { get; set; }

    public Nullable<long> card_id { get; set; }

    public Nullable<double> amount { get; set; }

    public Nullable<System.DateTime> payment_date { get; set; }

    public System.DateTime dt_create { get; set; }

    public long create_by__USER_id { get; set; }

    public Nullable<System.DateTime> dt_update { get; set; }

    public Nullable<long> update_by__USER_id { get; set; }



    public virtual User_Card_Info User_Card_Info { get; set; }

}

}
