
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api.Models
{

using System;
    using System.Collections.Generic;
    
public partial class notification
{

    public long id { get; set; }

    public long rel_USER_id { get; set; }

    public long APPOINTMENT_id { get; set; }

    public Nullable<long> SOUL_id { get; set; }

    public string text { get; set; }

    public string link { get; set; }

    public Nullable<bool> is_unread { get; set; }

    public System.DateTime dt_create { get; set; }

    public long create_by__USER_id { get; set; }

    public Nullable<System.DateTime> dt_update { get; set; }

    public Nullable<long> update_by__USER_id { get; set; }



    public virtual USER USER { get; set; }

}

}
