
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PHYSICIAN
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PHYSICIAN()
    {

        this.PHYSICIAN_ext = new HashSet<PHYSICIAN_ext>();

    }


    public long id { get; set; }

    public string legal_entity_name { get; set; }

    public string healthsplash_contact { get; set; }

    public string addr_address1 { get; set; }

    public string addr_address2 { get; set; }

    public Nullable<long> addr_zip_id { get; set; }

    public string practice_type { get; set; }

    public string practice_npi { get; set; }

    public string federal_tax_number { get; set; }

    public string primary_phone { get; set; }

    public string customer_service_number { get; set; }

    public Nullable<int> number_clinicians { get; set; }

    public Nullable<int> number_exams_per_week { get; set; }

    public string geographic_market { get; set; }

    public string insurance_providers { get; set; }

    public string EMR_software_used { get; set; }

    public string prim_contact_name_first { get; set; }

    public string prim_contact_name_last { get; set; }

    public string prim_contact_phone { get; set; }

    public string prim_contact_email { get; set; }

    public string oper_contact_name_first { get; set; }

    public string oper_contact_name_last { get; set; }

    public string oper_contact_phone { get; set; }

    public string oper_contact_email { get; set; }

    public string fina_contact_name_first { get; set; }

    public string fina_contact_name_last { get; set; }

    public string fina_contact_phone { get; set; }

    public string fina_contact_email { get; set; }

    public string auth_contact_name_first { get; set; }

    public string auth_contact_name_last { get; set; }

    public string auth_contact_phone { get; set; }

    public string auth_contact_email { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PHYSICIAN_ext> PHYSICIAN_ext { get; set; }

    public virtual ref_zip ref_zip { get; set; }

}

}
