//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_TAG
    {
        public string tag { get; set; }
        public string pname { get; set; }
        public string rel_ref_tag_type_code { get; set; }
        public string tag_parent { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
