
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ref_specialty1
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ref_specialty1()
    {

        this.con_DOCTOR1_ref_specialty = new HashSet<con_DOCTOR1_ref_specialty>();

        this.con_ref_specialty_ref_condition = new HashSet<con_ref_specialty_ref_condition>();

        this.ref_condition = new HashSet<ref_condition>();

    }


    public long id { get; set; }

    public Nullable<long> rel_ref_provider_type_id { get; set; }

    public string level2_classification { get; set; }

    public string level2_classification_code { get; set; }

    public string level3_specialization { get; set; }

    public string level3_specialization_code { get; set; }

    public string xconditions { get; set; }

    public Nullable<bool> status { get; set; }

    public Nullable<long> create_by__USER_id { get; set; }

    public Nullable<System.DateTime> dt_create { get; set; }

    public Nullable<long> update_by__USER_id { get; set; }

    public Nullable<System.DateTime> dt_update { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<con_DOCTOR1_ref_specialty> con_DOCTOR1_ref_specialty { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<con_ref_specialty_ref_condition> con_ref_specialty_ref_condition { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ref_condition> ref_condition { get; set; }

    public virtual ref_specialty_provider ref_specialty_provider { get; set; }

}

}
