//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOUL_info_2
    {
        public long id { get; set; }
        public long rel_SOUL_id { get; set; }
        public Nullable<bool> authorized_representative { get; set; }
        public Nullable<bool> received_similar_product { get; set; }
        public Nullable<bool> received_similar_covered { get; set; }
        public string list_other_health_concerns { get; set; }
        public string name_on_ins_card { get; set; }
        public Nullable<System.DateTime> date_birth { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> weight { get; set; }
        public string doctor_name { get; set; }
        public string doctor_phone { get; set; }
        public string doctor_fax { get; set; }
        public string ins_primary { get; set; }
        public string pins_policy_number { get; set; }
        public Nullable<long> pins_rel_ADDRESS_id { get; set; }
        public string pins_phone { get; set; }
        public string sins_policy_number { get; set; }
        public Nullable<long> sins_rel_ADDRESS_id { get; set; }
        public string sins_phone { get; set; }
        public Nullable<int> waist_size { get; set; }
        public string pins_name { get; set; }
        public string sins_name { get; set; }
        public string pins_group_no { get; set; }
        public string sins_group_no { get; set; }
        public Nullable<bool> interested_in_AED { get; set; }
        public string doctor_NPI { get; set; }
        public Nullable<long> doctor_rel_ADDRESS_id { get; set; }
        public string SSN { get; set; }
        public string doctor_state_m_id { get; set; }
        public string doctor_medicare_upin { get; set; }
        public string doctor_license_no { get; set; }
        public Nullable<bool> doctor_pecos_cert { get; set; }
        public string doctor_fax_to { get; set; }
        public string doctor_address_state { get; set; }
        public string doctor_address_city { get; set; }
        public string doctor_address { get; set; }
        public string doctor_address_zip { get; set; }
        public Nullable<long> pins_info_2_id { get; set; }
        public Nullable<long> sins_info_2_id { get; set; }
        public string injury_covered_under { get; set; }
        public string injury_covered_claimno { get; set; }
        public string gender { get; set; }
        public Nullable<bool> diabetic { get; set; }
        public Nullable<bool> cpap { get; set; }
        public Nullable<bool> diabetic_confirm { get; set; }
        public Nullable<bool> ppo { get; set; }
        public Nullable<bool> jpc_interested { get; set; }
    }
}
