
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SUPPLIER
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SUPPLIER()
    {

        this.SUPPLIER_ext = new HashSet<SUPPLIER_ext>();

    }


    public long id { get; set; }

    public string legal_entity_name { get; set; }

    public string healthsplash_contact { get; set; }

    public string addr_address1 { get; set; }

    public string addr_address2 { get; set; }

    public Nullable<long> addr_zip_id { get; set; }

    public string federal_tax_number { get; set; }

    public string primary_phone { get; set; }

    public string telemedicine_partner { get; set; }

    public string organization_npi { get; set; }

    public string insurance_provider { get; set; }

    public string preferred_geographic_market { get; set; }

    public string products_hcpcs { get; set; }

    public string patient_deductible_threshold { get; set; }

    public string prim_contact_name_first { get; set; }

    public string prim_contact_name_last { get; set; }

    public string prim_contact_phone { get; set; }

    public string prim_contact_email { get; set; }

    public string oper_contact_name_first { get; set; }

    public string oper_contact_name_last { get; set; }

    public string oper_contact_phone { get; set; }

    public string oper_contact_email { get; set; }

    public string fina_contact_name_first { get; set; }

    public string fina_contact_name_last { get; set; }

    public string fina_contact_phone { get; set; }

    public string fina_contact_email { get; set; }

    public string auth_contact_name_first { get; set; }

    public string auth_contact_name_last { get; set; }

    public string auth_contact_phone { get; set; }

    public string auth_contact_email { get; set; }



    public virtual ref_zip ref_zip { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SUPPLIER_ext> SUPPLIER_ext { get; set; }

}

}
