
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TRANSACTION
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TRANSACTION()
    {

        this.TRANSACTION_ext = new HashSet<TRANSACTION_ext>();

    }


    public long id { get; set; }

    public long rel_ref_TRANSACTION_type_id { get; set; }

    public Nullable<long> rel_ref_status_id { get; set; }

    public Nullable<long> create_by__USER_id { get; set; }

    public Nullable<System.DateTime> dt_create { get; set; }

    public Nullable<long> update_by__USER_id { get; set; }

    public Nullable<System.DateTime> dt_update { get; set; }



    public virtual ref_status ref_status { get; set; }

    public virtual ref_TRANSACTION_type ref_TRANSACTION_type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TRANSACTION_ext> TRANSACTION_ext { get; set; }

}

}
