
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User_Card_Info
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User_Card_Info()
    {

        this.log_payment = new HashSet<log_payment>();

    }


    public long id { get; set; }

    public long user_id { get; set; }

    public string card_number { get; set; }

    public string cvv { get; set; }

    public Nullable<System.DateTime> expiry_date { get; set; }

    public Nullable<System.DateTime> payment_date { get; set; }

    public System.DateTime dt_create { get; set; }

    public long create_by__USER_id { get; set; }

    public Nullable<System.DateTime> dt_update { get; set; }

    public Nullable<long> update_by__USER_id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<log_payment> log_payment { get; set; }

    public virtual USER USER { get; set; }

}

}
