//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class con_ORDERPROC_DOCTOR
    {
        public long rel_ORDERPROC_id { get; set; }
        public long rel_SOUL_id { get; set; }
        public long rel_DOCTOR_id { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual ORDERPROC ORDERPROC { get; set; }
        public virtual SOUL SOUL { get; set; }
    }
}
