//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_insurance_plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ref_insurance_plan()
        {
            this.Doc_Insurance_Affiliation = new HashSet<Doc_Insurance_Affiliation>();
            this.Doc_Insurance = new HashSet<Doc_Insurance>();
        }
    
        public long id { get; set; }
        public string uid { get; set; }
        public string name { get; set; }
        public Nullable<int> provider_id { get; set; }
        public string category { get; set; }
    
        public virtual ref_insurancecompanies ref_insurancecompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_Insurance_Affiliation> Doc_Insurance_Affiliation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_Insurance> Doc_Insurance { get; set; }
    }
}
