//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public long id { get; set; }
        public long rel_TRANSACTION_id { get; set; }
        public long rel_ref_orproc_state_id { get; set; }
        public long taken_by { get; set; }
        public long taken_on { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<long> last_update_by { get; set; }
    }
}
