//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wellness_exam
    {
        public long id { get; set; }
        public long rel_SOUL_id { get; set; }
        public long rel_exam_id { get; set; }
        public System.DateTime dt_taken { get; set; }
        public long create_by__USER { get; set; }
        public Nullable<System.DateTime> dt_create { get; set; }
        public Nullable<System.DateTime> update_by__USER { get; set; }
        public Nullable<System.DateTime> dt_update { get; set; }
    
        public virtual ref_wellness_exam ref_wellness_exam { get; set; }
        public virtual SOUL SOUL { get; set; }
    }
}
