//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADDRESS()
        {
            this.DOCTORs = new HashSet<DOCTOR>();
            this.SOULs = new HashSet<SOUL>();
        }
    
        public long id { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string xus_city { get; set; }
        public string xus_state { get; set; }
        public string xus_zip { get; set; }
        public long rel_ref_zip_id { get; set; }
        public string OR_zip_city { get; set; }
        public long rel_ref_country_id { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<long> last_updated_by { get; set; }
    
        public virtual ref_zip ref_zip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTOR> DOCTORs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOUL> SOULs { get; set; }
    }
}
