//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class con_SOUL_ref_upsell
    {
        public long id { get; set; }
        public long rel_SOUL_id { get; set; }
        public long rel_ref_upsell_id { get; set; }
        public string meta { get; set; }
        public string meta_2 { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual ref_upsell ref_upsell { get; set; }
        public virtual SOUL SOUL { get; set; }
    }
}
