
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api.Models
{

using System;
    using System.Collections.Generic;
    
public partial class con_ORDER_PRODUCT
{

    public long id { get; set; }

    public Nullable<long> rel_ORDER_id { get; set; }

    public Nullable<long> rel_PRODUCT_id { get; set; }

    public System.DateTime dt_create { get; set; }

    public Nullable<System.DateTime> dt_update { get; set; }

    public long create_by__USER_id { get; set; }

    public Nullable<long> update_by__USER_id { get; set; }



    public virtual ORDER_ext ORDER_ext { get; set; }

    public virtual PRODUCT_ext PRODUCT_ext { get; set; }

}

}
