
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api.Models
{

using System;
    using System.Collections.Generic;
    
public partial class con_SOUL_mailing_list
{

    public int id { get; set; }

    public Nullable<int> soul_id { get; set; }

    public Nullable<int> rel_ref_status_id { get; set; }

    public Nullable<System.DateTime> date_created { get; set; }

    public Nullable<System.DateTime> date_updated { get; set; }

    public string subcriber_hash { get; set; }

}

}
