//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_ORPROC_ALL
    {
        public long id { get; set; }
        public long rel_ORDERPROC_id { get; set; }
        public string action { get; set; }
        public string meta { get; set; }
        public long executed_by { get; set; }
        public System.DateTime executed_on { get; set; }
        public string var_from { get; set; }
        public string var_to { get; set; }
    }
}
