//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_info_2
    {
        public long id { get; set; }
        public long rel_ORDERPROC_id { get; set; }
        public Nullable<System.DateTime> date_actual_ship { get; set; }
        public string shipped_through { get; set; }
        public string tracking_no { get; set; }
        public Nullable<System.DateTime> date_AOB_received { get; set; }
    
        public virtual ORDERPROC ORDERPROC { get; set; }
    }
}
