
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ref_languages
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ref_languages()
    {

        this.con_DOCTOR_ref_language = new HashSet<con_DOCTOR_ref_language>();

        this.con_DOCTOR1_ref_language = new HashSet<con_DOCTOR1_ref_language>();

    }


    public long id { get; set; }

    public string dname { get; set; }

    public System.DateTime dt_create { get; set; }

    public long create_by__USER_id { get; set; }

    public Nullable<System.DateTime> dt_update { get; set; }

    public Nullable<long> update_by__USER_id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<con_DOCTOR_ref_language> con_DOCTOR_ref_language { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<con_DOCTOR1_ref_language> con_DOCTOR1_ref_language { get; set; }

}

}
