
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ref_specialty
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ref_specialty()
    {

        this.con_DOCTOR_ref_specialty = new HashSet<con_DOCTOR_ref_specialty>();

    }


    public long id { get; set; }

    public string code { get; set; }

    public string name { get; set; }

    public string level { get; set; }

    public string group { get; set; }

    public string provider_type { get; set; }

    public string specialization { get; set; }

    public string conditions { get; set; }

    public Nullable<long> rel_ref_specialty_category_id { get; set; }

    public Nullable<long> create_by__USER_id { get; set; }

    public Nullable<System.DateTime> dt_create { get; set; }

    public Nullable<long> update_by__USER_id { get; set; }

    public Nullable<System.DateTime> dt_update { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<con_DOCTOR_ref_specialty> con_DOCTOR_ref_specialty { get; set; }

}

}
