//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOUL_info_3
    {
        public long id { get; set; }
        public long rel_SOUL_id { get; set; }
        public string home_phone2 { get; set; }
        public string home_phone_co { get; set; }
        public string emgcy_contact1_name { get; set; }
        public string emgcy_contact1_relation { get; set; }
        public string emgcy_contact1_phone1 { get; set; }
        public string emgcy_contact1_phone2 { get; set; }
        public string emgcy_contact1_phone3 { get; set; }
        public Nullable<bool> emgcy_contact1_hasaccess { get; set; }
        public string emgcy_contact2_name { get; set; }
        public string emgcy_contact2_relation { get; set; }
        public string emgcy_contact2_phone1 { get; set; }
        public string emgcy_contact2_phone2 { get; set; }
        public string emgcy_contact2_phone3 { get; set; }
        public Nullable<bool> emgcy_contact2_hasaccess { get; set; }
        public string emgcy_contact3_name { get; set; }
        public string emgcy_contact3_relation { get; set; }
        public string emgcy_contact3_phone1 { get; set; }
        public string emgcy_contact3_phone2 { get; set; }
        public string emgcy_contact3_phone3 { get; set; }
        public Nullable<bool> emgcy_contact3_hasaccess { get; set; }
        public string pref_hospital_name { get; set; }
        public string pref_hospital_city { get; set; }
        public string pref_hospital_state { get; set; }
        public string pref_hospital_phone { get; set; }
        public string allergies { get; set; }
        public string emgcy_special_instructions { get; set; }
        public string home_hidden_key_loc { get; set; }
        public string medical_conditions { get; set; }
    }
}
