

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace api.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SV_db1Entities : DbContext
{
    public SV_db1Entities()
        : base("name=SV_db1Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<con_APPOINTMENT_NOTE> con_APPOINTMENT_NOTE { get; set; }

    public virtual DbSet<con_DOCTOR_ref_insurance> con_DOCTOR_ref_insurance { get; set; }

    public virtual DbSet<con_USER_favorite_DOCTOR> con_USER_favorite_DOCTOR { get; set; }

    public virtual DbSet<DOCTOR_ext> DOCTOR_ext { get; set; }

    public virtual DbSet<DOCTOR_ext_NPI> DOCTOR_ext_NPI { get; set; }

    public virtual DbSet<ref_specialty_category> ref_specialty_category { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<app_authentication> app_authentication { get; set; }

    public virtual DbSet<APPOINTMENT> APPOINTMENTs { get; set; }

    public virtual DbSet<APPOINTMENT_ext> APPOINTMENT_ext { get; set; }

    public virtual DbSet<con_DOCTOR_Hospital> con_DOCTOR_Hospital { get; set; }

    public virtual DbSet<con_DOCTOR_NOTE> con_DOCTOR_NOTE { get; set; }

    public virtual DbSet<con_DOCTOR_ref_condition> con_DOCTOR_ref_condition { get; set; }

    public virtual DbSet<con_DOCTOR_ref_Hospital> con_DOCTOR_ref_Hospital { get; set; }

    public virtual DbSet<con_DOCTOR_ref_language> con_DOCTOR_ref_language { get; set; }

    public virtual DbSet<con_DOCTOR_ref_specialty> con_DOCTOR_ref_specialty { get; set; }

    public virtual DbSet<con_DOCTOR_timeslot> con_DOCTOR_timeslot { get; set; }

    public virtual DbSet<con_DOCTOR1_ref_insurance> con_DOCTOR1_ref_insurance { get; set; }

    public virtual DbSet<con_DOCTOR1_ref_language> con_DOCTOR1_ref_language { get; set; }

    public virtual DbSet<con_DOCTOR1_ref_specialty> con_DOCTOR1_ref_specialty { get; set; }

    public virtual DbSet<con_ORDER_NOTE> con_ORDER_NOTE { get; set; }

    public virtual DbSet<con_ORDER_PRODUCT> con_ORDER_PRODUCT { get; set; }

    public virtual DbSet<con_ref_specialty_ref_condition> con_ref_specialty_ref_condition { get; set; }

    public virtual DbSet<con_SOUL_LIST> con_SOUL_LIST { get; set; }

    public virtual DbSet<con_SOUL_mailing_list> con_SOUL_mailing_list { get; set; }

    public virtual DbSet<con_SOUL_ref_insurance> con_SOUL_ref_insurance { get; set; }

    public virtual DbSet<con_TRANSACTION_NOTE> con_TRANSACTION_NOTE { get; set; }

    public virtual DbSet<DOCTOR> DOCTORs { get; set; }

    public virtual DbSet<DOCTOR_ext1> DOCTOR_ext1 { get; set; }

    public virtual DbSet<DOCTOR_NPI> DOCTOR_NPI { get; set; }

    public virtual DbSet<DOCTOR1> DOCTOR1 { get; set; }

    public virtual DbSet<hs_DOCTOR> hs_DOCTOR { get; set; }

    public virtual DbSet<hs_DOCTOR_ext> hs_DOCTOR_ext { get; set; }

    public virtual DbSet<hs_Hospital> hs_Hospital { get; set; }

    public virtual DbSet<hs_HOSPITAL_ext> hs_HOSPITAL_ext { get; set; }

    public virtual DbSet<hs_ORGANIZATION> hs_ORGANIZATION { get; set; }

    public virtual DbSet<LIST> LISTs { get; set; }

    public virtual DbSet<LIST_ext> LIST_ext { get; set; }

    public virtual DbSet<log_CALL> log_CALL { get; set; }

    public virtual DbSet<log_payment> log_payment { get; set; }

    public virtual DbSet<log_token> log_token { get; set; }

    public virtual DbSet<MARKETER> MARKETERs { get; set; }

    public virtual DbSet<MARKETER_ext> MARKETER_ext { get; set; }

    public virtual DbSet<NOTE> NOTEs { get; set; }

    public virtual DbSet<notification> notifications { get; set; }

    public virtual DbSet<ORDER> ORDERs { get; set; }

    public virtual DbSet<ORDER_ext> ORDER_ext { get; set; }

    public virtual DbSet<PHARMACY> PHARMACies { get; set; }

    public virtual DbSet<PHARMACY_ext> PHARMACY_ext { get; set; }

    public virtual DbSet<PHYSICIAN> PHYSICIANs { get; set; }

    public virtual DbSet<PHYSICIAN_ext> PHYSICIAN_ext { get; set; }

    public virtual DbSet<PRODUCT> PRODUCTs { get; set; }

    public virtual DbSet<PRODUCT_ext> PRODUCT_ext { get; set; }

    public virtual DbSet<ref_APPOINTMENT_status> ref_APPOINTMENT_status { get; set; }

    public virtual DbSet<ref_APPOINTMENT_type> ref_APPOINTMENT_type { get; set; }

    public virtual DbSet<ref_CALL_type> ref_CALL_type { get; set; }

    public virtual DbSet<ref_condition> ref_condition { get; set; }

    public virtual DbSet<ref_data_type> ref_data_type { get; set; }

    public virtual DbSet<ref_insurance_provider> ref_insurance_provider { get; set; }

    public virtual DbSet<ref_languages> ref_languages { get; set; }

    public virtual DbSet<ref_NOTE_type> ref_NOTE_type { get; set; }

    public virtual DbSet<ref_specialty> ref_specialty { get; set; }

    public virtual DbSet<ref_specialty_provider> ref_specialty_provider { get; set; }

    public virtual DbSet<ref_specialty1> ref_specialty1 { get; set; }

    public virtual DbSet<ref_status> ref_status { get; set; }

    public virtual DbSet<ref_status_type> ref_status_type { get; set; }

    public virtual DbSet<ref_TRANSACTION_type> ref_TRANSACTION_type { get; set; }

    public virtual DbSet<ref_USER_type> ref_USER_type { get; set; }

    public virtual DbSet<ref_wellness_exam> ref_wellness_exam { get; set; }

    public virtual DbSet<ref_zip> ref_zip { get; set; }

    public virtual DbSet<SOUL> SOULs { get; set; }

    public virtual DbSet<SOUL_ext> SOUL_ext { get; set; }

    public virtual DbSet<SUPPLIER> SUPPLIERs { get; set; }

    public virtual DbSet<SUPPLIER_ext> SUPPLIER_ext { get; set; }

    public virtual DbSet<top_search> top_search { get; set; }

    public virtual DbSet<TRANSACTION> TRANSACTIONs { get; set; }

    public virtual DbSet<TRANSACTION_ext> TRANSACTION_ext { get; set; }

    public virtual DbSet<USER> USERs { get; set; }

    public virtual DbSet<User_Card_Info> User_Card_Info { get; set; }

    public virtual DbSet<USER_ext> USER_ext { get; set; }

    public virtual DbSet<USER_type_access> USER_type_access { get; set; }

    public virtual DbSet<wellness_exam> wellness_exam { get; set; }

    public virtual DbSet<log_token_activity> log_token_activity { get; set; }

}

}

