//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAG
    {
        public long id { get; set; }
        public string value { get; set; }
        public long rel_ORDERPROC_id { get; set; }
        public Nullable<long> rel_NOTE_id { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public string type { get; set; }
        public System.DateTime created_on { get; set; }
        public long created_by { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<long> updated_by { get; set; }
    
        public virtual ORDERPROC ORDERPROC { get; set; }
    }
}
